### ISSUE TITLE
Registering a wrapping key - aes and rsa public key.

### ISSUE THREAD

**Issue by pkumarex** [ThalesGroup/kmip-go#8]
Hi,

I am trying to register a wrapping key.
Tried the following request for aes wrapping key.
 msg = kmip.RequestMessage{
        RequestHeader: kmip.RequestHeader{
            ProtocolVersion: kmip.ProtocolVersion{
                ProtocolVersionMajor: 1,
                ProtocolVersionMinor: 4,
            },
            BatchCount: 1,
            //Authentication: auth,
        },
        BatchItem: []kmip.RequestBatchItem{
            {
                Operation: kmip14.OperationRegister,
                RequestPayload: kmip.RegisterRequestPayload{
                    ObjectType: kmip14.ObjectTypeSymmetricKey,
                    TemplateAttribute: kmip.TemplateAttribute{
                        Attribute: []kmip.Attribute{
                            {
                                AttributeName:  "Cryptographic Algorithm",
                                AttributeValue: kmip14.CryptographicAlgorithmECDSA,
                            },
                            {
                                AttributeName:  "Cryptographic Length",
                                AttributeValue: int32(256),
                            },
                            {
                                AttributeName:  "Cryptographic Usage Mask",
                                AttributeValue: kmip14.CryptographicUsageMaskWrapKey | kmip14.CryptographicUsageMaskUnwrapKey,
                            },
                        },
                    },
                    SymmetricKey: &kmip.SymmetricKey{
                        KeyBlock: kmip.KeyBlock{
                            KeyFormatType:          kmip14.KeyFormatTypeRaw,
                            CryptographicAlgorithm: kmip14.CryptographicAlgorithmAES,
                            CryptographicLength:    256,
                            KeyValue: kmip.KeyValue{
                                KeyMaterial: "7b4d51b827fb232b109929229864dba3",
                            },
                        },
                    },
                },
            },
        },
    }

This seems to work in thales server but not in pykmip server. is anything need to be included for pykmip server.

Can you please provide an example of registering a rsa public wrapping key ?

**Comment by ansel1** [comment]
I don't think this is an issue in kmip-go.  Sounds like you are encountering differences between the Thales KMIP server implementation, and the py-kmip server implementation.  Which is to be expected: that's the problem with the KMIP spec, it's so broad and flexible that no two implementations of it actually behave the same.  Your best bet is to stick to the examples in the test case documents: http://docs.oasis-open.org/kmip/testcases/v1.4/cn01/kmip-testcases-v1.4-cn01.html#_Toc479076963

I have looked a bit at py-kmip's code.  It's pretty strict about order, and doesn't support many attributes, operations, and scenarios.  I'm afraid you'll need to debug through it to really understand why one operation works while another doesn't.

The request above looks a little fishy though.  You are registering a managed object which is an AES key.  I don't think the Cryptographic Algorithm or Cryptographic Length attributes in the TemplateAttribute struct make sense.  Those are attributes already listed in the KeyBlock, and they contradict.  I'm not even sure what the implementation is expected to do when attributes in TemplateAttribute conflict with the same attributes in the KeyBlock.  It's not mentioned in the spec.  I'm guessing this works with the Thales server because it's ignoring the conflicting TemplateAttributes.

I'm afraid scope of this package is just to ensure proper encoding and decoding of TTLV.  You will probably need to pursue Thales support or the py-kmip maintainers to understand how to make operations work.
